### ISSUE TITLE
error

### ISSUE THREAD

**Issue by qwikser** [firsttris/homebridge-hyperion-light#1]
Hi,

wollte grade mal dein plugin testen, bekomme beim starten der homebridge aber immer diesen hier:

`
[2017-01-07 21:08:44] Loading 1 accessories...
[2017-01-07 21:08:44] [TV Wand] Initializing Hyperion accessory...
[2017-01-07 21:08:44] [TV Wand] Starting Hyperion Accessory
/usr/lib/node_modules/homebridge-hyperion-light/index.js:106
    if (this.effectName !== null && this.effectName.length > 0) {
                                                   ^

TypeError: Cannot read property 'length' of undefined
    at HyperionAccessory.getServices (/usr/lib/node_modules/homebridge-hyperion-light/index.js:106:52)
    at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:378:36)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:266:26)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
`

Aus der cfg habe ich auch die effects Zeile gelöscht, aktuell ist diese so:
`
"accessories": [
        {
            "accessory": "Hyperion",
            "name": "TV Wand",
            "ambilightName": "TV Wand MB Light",
            "host": "192.168.178.60",
            "port": "19444"
        }
    ]
`

**Comment by firsttris** [comment]
Hallo,

danke für dein feedback!
ich hatte das nicht richtig abgefangen wenn kein effect definiert ist.. 
Nun sollte es funktionieren.
Einfach über npm aktualisieren...

Grüße
Tristan

**Comment by qwikser** [comment]
heisst es nicht:
npm update -g homebridge-hyperion-light
??
