### ISSUE TITLE
Receiving error

### ISSUE THREAD

**Issue by toldenburger** [firsttris/homebridge-hyperion-light#5]
Thank you for the homebridge-hyperion plugin!

I'm receiving an error via homebridge when trying to switch the light (on/off or any color):

2017-04-06 10:00:07	stdout	    at HAPServer._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)
2017-04-06 10:00:07	stdout	    at HAPServer.emit (events.js:201:7)
2017-04-06 10:00:07	stdout	    at emitMany (events.js:127:13)
2017-04-06 10:00:07	stdout	    at Bridge.Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:685:8)
2017-04-06 10:00:07	stdout	    at Array.forEach (native)
2017-04-06 10:00:07	stdout	    at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:740:22)
2017-04-06 10:00:07	stdout	    at Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:155:10)
2017-04-06 10:00:07	stdout	    at emit (events.js:201:7)
2017-04-06 10:00:07	stdout	    at emitMany (events.js:127:13)
2017-04-06 10:00:07	stdout	    at lightService.getCharacteristic.on (/usr/lib/node_modules/homebridge-hyperion-light/index.js:46:38)
2017-04-06 10:00:07	stdout	TypeError: Cannot read property 'updateCharacteristic' of undefined
2017-04-06 10:00:07	stdout	
2017-04-06 10:00:07	stdout	                                     ^
2017-04-06 10:00:07	stdout	                this.ambilightService.updateCharacteristic(Characteristic.On, 0);
2017-04-06 10:00:07	stdout	/usr/lib/node_modules/homebridge-hyperion-light/index.js:46

The fault is probably all mine, any tips?

**Comment by firsttris** [comment]
which nodejs version are using?

i just tested my homebrdige and the hyperion plugin works well.

regards
tristan

**Comment by firsttris** [comment]
could you resolve your issue?
i think its most likely because of an old nodejs version. 
i used ecmascript 6 in my project

if you still need help please re-open or drop a mail.

best regards
tristan
