### ISSUE TITLE
Cannot read property 'length' of undefined nach Update auf Homebridge 4.25

### ISSUE THREAD

**Issue by jansppenrade2** [firsttris/homebridge-hyperion-light#7]
Hallo Tristan,

nach dem Update von Homebridge 4.20 auf 4.25 tritt nun folgender Fehler auf:

/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:225
      if (myString.length>maxLength) myString = myString.substring(0,maxLength); //Truncate strings that are too long
                  ^

TypeError: Cannot read property 'length' of undefined
    at Characteristic.Model.Characteristic.validateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:225:19)
    at Characteristic.Model.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:273:19)
    at Service.AccessoryInformation.Service.setCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:178:32)
    at HyperionAccessory.getServices (/usr/local/lib/node_modules/homebridge-hyperion-light/index.js:109:10)
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:378:36)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:266:26)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)

Mache ich irgend etwas falsch? Hab' ich was übersehen?

**Comment by firsttris** [comment]
Holla,

sorry für die späte antwort.

ich habe nun auf homebrdige 0.4.27 aktualisiert.

bei mir funktioniert das plugin. es gab auch keine api Änderungen.


vielleicht mal deine config prüfen und ob der jsonserver und webserver in hyperion aktiviert sind.
du kannst ja einfach eine hyperion mobile app laden und testen. wenn es dort funktioniert sollte das plugin es auch ansprechen können.

Falls du weiterhin probleme hast einfach ein Ticket eröffnen.

Grüße
